### PR TITLE
Fix: fatal error: 'flutter_sms-Swift.h' file not found

### PR DESCRIPTION
**Pull request by blacklizard**
Make this package run-able with ios

### CODE REVIEW

**Comment by shounakmulay** [comment]
iOS does not give access to user's messages.
And in the current state the plugin has no iOS functionality.

So I don't think there is any need to make it work on iOS for now.

**Comment by blacklizard** [comment]
hi.. thanks for the response, this PR is not intended to make user message accessible, this PR is intended for the package to be able to compile on IOS device, currently if you try to run flutter app in IOS simulator when this package is installed, it does not run and throw `fatal error: 'flutter_sms-Swift.h' file not found` error. I am currently developing an app that will run in both IOS and android, but sms functionality is only being used on android. hope this can be merged

**Comment by shounakmulay** [comment]
Got it. My bad.

I'll take a look.

Thanks.

**Review by shounakmulay — APPROVED** [review]
Looks good.

**Comment by shounakmulay** [comment]
I have published a new version with the fix.
`telephony: ^0.0.7`

Thanks for the PR @blacklizard

**Comment by blacklizard** [comment]
Thanks @shounakmulay

**Pull request merged**
